### ISSUE TITLE
rex_text in UITextView is not called for initial value

### ISSUE THREAD

**Issue by Igor-Palaguta** [neilpa/Rex#149] opened 2016-07-25 08:14 UTC
I know that all this will be changed in nearest future, but in any case rex has following issue.

```
      self.textView.text = "Hello world"
      self.textView
         .rex_text
         .startWithNext { _ in
            //is not called for "Hello world"
      }
```

**Comment by ikesyo** [comment] 2016-07-25 09:22
Closing this as a duplicate of #144.

**Closed as completed by ikesyo** 2016-07-25 09:22 UTC
